FROM nginx

ARG appname=catapp
ARG appversion=1.0.0

RUN mkdir /usr/share/nginx/html/orange
RUN mkdir /usr/share/nginx/html/red
RUN echo "welcome to <font color=ORANGE>ORANGE</font> @ ${appname}:${appversion}" > /usr/share/nginx/html/orange/index.html
RUN echo "welcome to <font color=RED>RED</font> @ ${appname}:${appversion}" > /usr/share/nginx/html/red/index.html
RUN echo "welcome to ${appname}:${appversion}" > /usr/share/nginx/html/index.html
